openapi: 3.0.0
info:
  title: Books API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server

paths:
  /books:
    get:
      summary: Returns a list of books.
      responses:
        '200':
          description: A JSON array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Creates a new book.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Sample Book Title"
      responses:
        '201':
          description: Book created successfully
        '422':
          description: Validation error

  /books/{id}:
    get:
      summary: Returns a specific book.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the book to retrieve.
      responses:
        '200':
          description: A JSON object representing the book.
          content:
            application/json:
              schema:
                type: object
    patch:
      summary: Updates a specific book.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the book to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Updated Book Title"
      responses:
        '200':
          description: Book updated successfully
        '404':
          description: Book not found
        '422':
          description: Validation error
    delete:
      summary: Deletes a specific book.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the book to delete.
      responses:
        '200':
          description: Book deleted successfully
        '404':
          description: Book not found
